#!/bin/zsh
# company/shell/env.zsh — Environment variables (portable)
# Source: modules/home/default.nix → sessionVariables + initContent
#
# Cascading EDITOR detection. Custom paths loaded from
# ~/.config/dotfiles-company/paths.env (generated by setup.sh).

# ── Editor (cascading: best available) ───────────────────────────
if command -v nvim &>/dev/null; then
  export EDITOR='nvim'
  export VISUAL='nvim'
elif command -v vim &>/dev/null; then
  export EDITOR='vim'
  export VISUAL='vim'
else
  export EDITOR='nano'
  export VISUAL='nano'
fi

# ── Standard paths ───────────────────────────────────────────────
export DOWNLOADS="${DOWNLOADS:-$HOME/Downloads}"

# ── User-customized paths (generated by setup.sh) ───────────────
if [ -f "$HOME/.config/dotfiles-company/paths.env" ]; then
  source "$HOME/.config/dotfiles-company/paths.env"
fi

# ── Dynamic PATH ─────────────────────────────────────────────────
# Add Homebrew and user-local binaries to PATH
if [ -d "/opt/homebrew/bin" ]; then
  export PATH="/opt/homebrew/bin:$HOME/.local/bin:$PATH"
elif [ -d "/usr/local/bin" ]; then
  export PATH="/usr/local/bin:$HOME/.local/bin:$PATH"
else
  export PATH="$HOME/.local/bin:$PATH"
fi

# ── NVM (Node Version Manager) ──────────────────────────────────
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# ── SDKMAN (Java/Kotlin/Gradle manager) ─────────────────────────
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

# ── Local overrides ─────────────────────────────────────────────
# Load machine-specific overrides (e.g., company proxy, custom vars)
if [ -f "$HOME/.env.local" ]; then
  source "$HOME/.env.local"
fi
