#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# flash focus current window
# yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.1 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                float             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.80           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_type                   auto           \
    auto_balance                 off            \
    split_ratio                  0.60           \
    top_padding                  0             \
    bottom_padding               0             \
    left_padding                 0             \
    right_padding                0             \
    window_gap                   8             \
    layout                       bsp            \
    mouse_modifier               alt             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# Exclude problematic apps from being managed:
system_apps="^(LuLu|Vimac|Calculator|Software Update|Dictionary|System (Preferences|Settings)|Photo Booth|Archive Utility|App Store|Activity Monitor|System Information|Finder)$"
yabai -m rule --add app="${system_apps}" manage=off
yabai -m rule --add app="^Raycast$" manage=off

yabai -m rule --add app="^Firefox|Floorp$" title="^Extension: \(Bitwarden"  manage=off

yabai -m rule --add app="^(Riot Client|League Of Legends|League of Legends)$" manage=off

yabai -m rule --add app="^Anki$" title="Add" layout=float

yabai -m rule --add title="(Settings|Save)" manage=off

# Web browsers
yabai -m rule --add label="Browsers" app="^(Google Chrome|Firefox Developer Edition|Safari|Arc|Firefox)$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|History|Picture-in-Picture|Library)$" manage=off

yabai -m rule --add label="calendar" app="^(Fantastical)"  manage=off
# yabai -m rule --add app="^Arc$" mouse_follows_focus=off
# yabai -m rule --add app="^Arc$" subrole="AXSystemDialog" mouse_follows_focus=off


yabai -m rule --add app="zoom.us" sticky=on layout=float

yabai -m rule --add app="^Clock|zoom\.us$" manage=off
yabai -m rule --add app="^Preview$" manage=off

# Text editors
yabai -m rule --add app="^(Code)$" space=2
# Social
yabai -m rule --add app="^(Slack|Discord)$" space=5

yabai -m rule --add app="^(Spotify)$" space=9
# Clean up empty spaces with no windows on them.
yabai -m signal --add event=space_changed action="sh $HOME/.config/yabai/cleanEmptySpaces.sh"




yabai -m rule --apply


echo "yabai configuration loaded.."

